### ISSUE TITLE
ENU to NED transform issues on VISION_POSITION_ESTIMATE

### ISSUE THREAD

**Issue by marufino** [mavlink/mavros#1067]
I'm working on using a camera to provide local position to the PX4's Local Position Estimator.

Based on the following instructions https://dev.px4.io/en/ros/external_position_estimation.html I provided the Vision position estimates in ENU, expecting mavros to convert them to NED.

What I found was that the positions were being converted correctly, but the rotations were not.
The resultant rotations were in ESD instead of NED. There was also a yaw offset of Pi/2 in the resultant rotation.

Am I misunderstanding the documentation or is there something wrong with the conversions? 
I ended up getting things to work by providing the position in NED and the orientation in a frame that resulted in NED after the Mavros conversion, and also had to correct for the Pi/2 yaw offset.

Even though it works with that "hack", I figured it might make sense to try to get to the bottom of what mavros or I are doing wrong. Thoughts?

Mavros: 0.26 (built from master)
ROS: Kinetic
Ubuntu: 16.04
[ X] PX4

**Comment by TSC21** [comment]
The rotations are supposed to be fed the body frame. ROS convention to the body frame is FLU (X front, Y left, Z up), the so called `base_link`. In the `vision_pose_estimate` plugin, MAVROS rotates from the `base_link` body to the aircraft body frame, which is FRD (X front, Y right, Z down). That rotation basically is a +PI rotation over the X axis.
So, to use the `vision_pose_plugin` as is, you need to feed the orientation in the `base_link` body frame (with represents the orientation wrt ENU local origin), so that MAVROS converts it to the aircraft body frame, wrt a NED local origin.
