### ISSUE TITLE
EKF2 VIO with MAVROS

### ISSUE THREAD

**Issue by Haeryangkim** [mavlink/mavros#1098]
Hi all,
With the update of ekf2(ver 1.8), VIO has been officially supported by the px4 ekf2.
https://www.dronecode.org/introducing-px4-v1-8-with-vio-and-obstacle-avoidance/

I've been using px4 + LPE with mavros and fused my visual odometry data into
**/mavros/vision_pose/pose**  topic - it might be incorrect way in my opinion.

But , although the ekf2 has been updated to support vio, I can't see any topics related to VIO in MAVROS.
1. Is current version of MAVROS working with EKF2 ( For VIO module)
2. Is there any way that I can I feed my visual odometry into px4 using MAVROS?

Thanks.

**Comment by TSC21** [comment]
@Haeryangkim just to clarify that MAVROS is platform agnostic, so is not dependent on the platform support but rather what Mavlink has to offer on it's API.

> But , although the ekf2 has been updated to support vio, I can't see any topics related to VIO in MAVROS.

For you, what's a "topic related with VIO"? We have support for `VISION_POSITION_ESTIMATE` and `ODOMETRY`, and both can send visual pose estimation to the FCU. If you want to use IMU camera triggering, you will have to dig deeper on how the timesync modes work on Mavlink, MAVROS and PX4.

> 1. Is current version of MAVROS working with EKF2 ( For VIO module)

There's no "VIO" module. What you have on EKF2 is a subscription to vision data, that is then used on the filter to estimate position (and yaw, if you fuse vision heading estimate as well). MAVROS supports sending vision data since almost it was created.

> 2. Is there any way that I can I feed my visual odometry into px4 using MAVROS?

You are already using one, so I don't really understand your question. You can use the `odom` plugin as well, which is on `mavros_extras`, to send `ODOMETRY` Mavlink messages to the FCU, which contain also velocity estimates and cross-covariance matrix data. But, if you don't have velocity data, the `vision_pose_estimate` plugin you are already using is enough.
