### ISSUE TITLE
Define setpoints also as a service

### ISSUE THREAD

**Issue by TSC21** [mavlink/mavros#126]
This offers two possibilities:
1. user control over the vehicle based on the setpoint commands issued
2. test the setpoints part of the firmware before moving to use a planner

I can advance by creating a new script called `mavsetp`. This one will be divided in 3: `local`, `global` and `attitude` (we still have the possibility of creating a setpoint global plugin). First two offer the services to control `pos`, `vel` and `accel`, while the second one offers control over `quat` and `rpy`.

So the command can be issued like:
```bash
$ rosrun mavros mavsetp local pos <x> <y> <z>
```
```bash
$ rosrun mavros mavsetp global vel <vx> <vy> <vz>
```
```bash
$ rosrun mavros mavsetp attitude quat <x> <y> <z> <w>
```

**Comment by v-to** [comment]
Hi Guys,

I can see it is closed, however I have problems with this issue.
We are working with Rover, where we don't have OFFBOARD.
Why can't we just leave as it was here https://github.com/mavlink/mavros/commit/d73b81903c3bb05eb31fcc5d5bc1da23d4abb201 
Or maybe we can force enabling GUIDED instead of OFFBOARD in case of Rover?

I can see that in the newest mavros the code is completely different and I am not sure howe are these issues solved there.

What would be your suggestion for us? Keep old version without offboard mode?

Kind regards

Witold
