### ISSUE TITLE
What is the difference between landing_target/pose and landing_target/lt_marker?

### ISSUE THREAD

**Issue by erikasnow** [mavlink/mavros#1326]
### Issue details

I can see the two topics when I run mavros, but I can't find any documentation on them. Has anyone used these before?

**Comment by TSC21** [comment]
The source code is your friend :)
`pose`: https://github.com/mavlink/mavros/blob/master/mavros_extras/src/plugins/landing_target.cpp#L104. Is the topic that the mavros_node subscribes in order to process and parse the data to the LANDING_TARGET msg that goes to the Mavlink stream (so, to the autopilot);
`lt_marker`: https://github.com/mavlink/mavros/blob/master/mavros_extras/src/plugins/landing_target.cpp#L93. Publishes a marker with the pose of the target (received from the LANDING_TARGET Mavlink msg that gets published from the autopilot, if any). This can be visualised in Rviz, for example.

**Comment by erikasnow** [comment]
So I'm publishing landing_target/pose messages to mavros using rqt and dummy data. Looking in QGroundControl, I'm not seeing the LANDING_TARGET Mavlink message. I've got precision land enabled. Am I misunderstanding how this should be working, or do I need to set other parameters?
