### ISSUE TITLE
setpoint control (thrust, attitude, position etc.) through mavros<->px4 on a pixhawk

### ISSUE THREAD

**Issue by pmukherj** [mavlink/mavros#180]
Hey everybody!

I was able to use rosservices to arm the quadrotor and turn on the motors but it seems to be ignoring my commands being sent over setpoint/att_throttle. ROS log is here: https://www.dropbox.com/s/fm0nbhwg31yo5zd/thrust_control_log.csv?dl=0

I've been scavenging through the px4-users and px4 wiki to get a snapshot of the easiest way to send control commands into a pixhawk. I realize there is a long thread here (https://groups.google.com/forum/#!topic/px4users/IC1iz_TsL_Y) and its focussed on using raw C and UART, I thought I'd ping here on how to best achieve this over mavros. 

From some of my scavenging I have figured to, 
a) Switch to the latest developer firmware (not sure if necessary?)
b) Turned off RC control (just for a bench test), this article (https://pixhawk.org/firmware/apps/mc_att_control), makes it sound like the mavlink (and therefore mavros) commands should get to the pixhawk before the RC control gets to it. I realise ideally, I would fly outside, switch to "PosCtl" and then "Offboard mode" using an aux switch on my RC.
c) Made a 'set_mode' service call to switch to "Guided, Auto" mode (216?). There isn't an explicit mode defined for "Offboard mode" in srv/SetMode.srv. Maybe I missed something?

If I can get this going I can help consolidate some of the documentation that I've been perusing. I feel like all the information is out there, it just needs to be put in one place, so people relatively new (like me) don't miss something simple.

**Comment by cnsimbe** [comment]
How does one change the RC_MAP_OFFB_SW parameter on apm mission planner?

**Comment by mhkabir** [comment]
It's only for the PX4 native stack.

APM does not have support for it.

**Comment by psei0r** [comment]
Hi pmukherj and mhkabir!

I am currently trying to control the pixhawk via MAVLINK / ROS too but I am encountering the problem that the pixhawk doesnt react to it... The difference between us might be that I do not fly with it but want to drive my rover...

Here is what I did:

1) Install latest PX4 Firmware (https://pixhawk.org/dev/nuttx/building_and_flashing_console)
2) connected throttle and steering servos to pin 3/4 of the pixhawk
3) Qgroundcontrol:
- configure PX4 to Airframe to Z-84 Wing (otherwise my car controller / BEC will beep complaining that no servos are connected)
- set parameter SYS_COMPANION to 921600 for serial communication (https://pixhawk.org/dev/companion_link)

4) roslaunch mavros px4.launch (with 921600@ttyUSB0) -> works!
5) rosservice call /mavros/set_mode "base_mode: 0 custom_mode: 'OFFBOARD'" 
6) pixhawk will go into offboard mode: [ INFO] [1424270398.049014022]: FCU: [cmd] nav state: OFFBOARD

but no servo is reacting to any of the topics above and i cannot control the car in any way....

Do you have some tips for me why this doesnt work? Do I have e.g. to disable RC completely befor this will work? (i won't be needing it anyway) ?


cheers,
Marcel

**Comment by mhkabir** [comment]
There isn't much testing on the system with offboard mode. Please make sure you arm and try. 
Can you try position setpoints first.

**Comment by mhkabir** [comment]
And check the Attitude target message in QGC if the values change with the setpoint.

**Comment by psei0r** [comment]
I have problem arming the rover, pixhawk is e.g. complaining that airspeed sensor would be missing.... but as I said before, I dont wanna fly I just wanna drive. There are no rotors/motors that need to be armed on my vehicle, or is that step mandatory on each vehicle ?

**Comment by mhkabir** [comment]
Yes of course. You need to arm the vehicle + de-safety , otherwise no outputs at all. You can disable airspeed sensor checks like this : https://pixhawk.org/dev/circuit_breakers

Your approach isn't very good. Never a good idea to use Plane firmware for a rover. Its a very hacky way of doing it. You could probably make your own rover start-up script + mixer.

**Comment by psei0r** [comment]
I had some email correspondency with Lorenz Meier, he suggested this approach. 

I also tried with APM Rover 2.47 firmware, but then I cannot comunicate with the pixhawk on the TELEM2 port...

So I went back to PX4 stack, which unfortunately has no pre-config for rovers.....(at least I cannot find them in qgroundcontrol)

My Long-Term goal is exactly what you suggegested, building a complete custom config for our rover, but I dont know how to do that yet... I will have a look on the link you send me to get rid of the airspeed sensor error. Do you have any documenation for me how to customize the start script as well? Thanks a lot !!

**Comment by mhkabir** [comment]
Have a look at this page : https://pixhawk.org/dev/mixing
I'd happy to help you when I get some free time later ;)

For APM:Rover, default connection is some other port I think.

**Comment by psei0r** [comment]
Thanks a lot !! I see you know alot of this stuff, you seem to be MY MAN! =)

I looked into the mixing stuff quickly, i guess something like the FMU passthrough mixing would be an interesting configuration to do the testing?

https://github.com/PX4/Firmware/blob/master/ROMFS/px4fmu_common/mixers/FMU_pass.mix

If I understood correctly, this configuration will directly mix the inputs 0-3 (yaw pitch roll thrust) without scaling to the servos on pins 1-4.

Since I only need yaw and thrust, I should create a mixer setup like this? :


Passthrough mixer for ROVER (only thrust and yaw)
========================================
M: 1
O: 10000 10000 0 -10000 10000
S: 0 2 10000 10000 0 -10000 10000
M: 1
O: 10000 10000 0 -10000 10000
S: 0 3 10000 10000 0 -10000 10000

**Comment by psei0r** [comment]
by the way, the page https://pixhawk.org/dev/ros/mavros_offboard needs to be updated, the needed mavros command is not shown (at the bot), i think it is 
rosservice call /mavros/set_mode "base_mode: 0 custom_mode: 'OFFBOARD'"  ?

**Comment by vooon** [comment]
Better use `mavsys mode -c OFFBOARD` to change mode. Actually it do same service call, but i think it more human friendly.

(Prefix with `rosrun mavros script-name`)

**Comment by psei0r** [comment]
rosrun mavros mavsys mode -c OFFBOARD works fine too! Just confirmed it =)

@mhkabir : I managed to turn off the safety checkings and I can now arm the pixhawk. But there is still no reaction of my servos to the setpoint topics, and I cannot check the ATTITUDE_TARGET message, since it doesnt seem to be streamed, allthough I have added the line

mavlink stream -d /dev/ttyS2 -s ATTITUTE_TARGET -r 10 

in my extras.txt on the SD card. How can I turn it on? Lorenz Meier mentioned something about the availability of streams depending on the firmware / airframe config...

cheers
Marcel

**Comment by vooon** [comment]
As i remember OFFBOARD have timeout (0.5 sec), and switches to POSHOLD.

**Comment by psei0r** [comment]
When I stop sending ROS message to /mavros/setpoint/cmd_vel after I have armed the vehicle, it will start beeping and mavros will say this:

[ERROR] [1424348769.670787591]: FCU: failsafe mode on
[ INFO] [1424348770.671263234]: FCU: [cmd] nav state: DESCEND

After that, when I start sending ROS messages again, it will change back to OFFBOARD.

[ERROR] [1424348992.873188172]: FCU: failsafe mode off
[ INFO] [1424348993.874866513]: FCU: [cmd] nav state: OFFBOARD


So the pixhawk actually reacts to the topics in some kind of way, but the servos don't work yet. I am currently trying to figure out if this is a mixer problem. Any ideas?

**Comment by mhkabir** [comment]
What messages do you yet in QGC with TELEM2?

**Comment by psei0r** [comment]
First of all, here is my extras.txt located on the SD card for starting the mavlink stream on TELEM2:

mavlink start -m custom -d /dev/ttyS2 -b921600 -x
usleep 100000
mavlink stream -d /dev/ttyS2 -s HEARTBEAT -r 5
usleep 100000
mavlink stream -d /dev/ttyS2 -s STATUSTEXT -r 1
usleep 100000
mavlink stream -d /dev/ttyS2 -s COMMAND_LONG -r 1
usleep 100000
mavlink stream -d /dev/ttyS2 -s SYS_STATUS -r 1
usleep 100000
mavlink stream -d /dev/ttyS2 -s HIGHRES_IMU -r 50
usleep 100000
mavlink stream -d /dev/ttyS2 -s ATTITUDE -r 50
usleep 100000
mavlink stream -d /dev/ttyS2 -s ATTITUDE_QUATERNION -r 50
usleep 100000
mavlink stream -d /dev/ttyS2 -s VFR_HUD -r 10
usleep 100000
mavlink stream -d /dev/ttyS2 -s GPS_RAW_INT -r 5
usleep 100000
mavlink stream -d /dev/ttyS2 -s GLOBAL_POSITION_INT -r 5
usleep 100000
mavlink stream -d /dev/ttyS2 -s LOCAL_POSITION_NED -r 5
usleep 100000
mavlink stream -d /dev/ttyS2 -s VICON_POSITION_ESTIMATE -r 1
usleep 100000
mavlink stream -d /dev/ttyS2 -s GPS_GLOBAL_ORIGIN -r 1
usleep 100000
mavlink stream -d /dev/ttyS2 -s SERVO_OUTPUT_RAW_0 -r 1
usleep 100000
mavlink stream -d /dev/ttyS2 -s SERVO_OUTPUT_RAW_1 -r 1
usleep 100000
mavlink stream -d /dev/ttyS2 -s SERVO_OUTPUT_RAW_2 -r 1
usleep 100000
mavlink stream -d /dev/ttyS2 -s SERVO_OUTPUT_RAW_3 -r 1
usleep 100000
mavlink stream -d /dev/ttyS2 -s HIL_CONTROLS -r 1
usleep 100000
mavlink stream -d /dev/ttyS2 -s POSITION_TARGET_GLOBAL_INT -r 1
usleep 100000
mavlink stream -d /dev/ttyS2 -s POSITION_TARGET_LOCAL_NED -r 1
usleep 100000
mavlink stream -d /dev/ttyS2 -s ATTITUDE_TARGET -r 10
usleep 100000
mavlink stream -d /dev/ttyS2 -s RC_CHANNELS_RAW -r 1
usleep 100000
mavlink stream -d /dev/ttyS2 -s MANUAL_CONTROL -r 1
usleep 100000
mavlink stream -d /dev/ttyS2 -s OPTICAL_FLOW -r 1
usleep 100000
mavlink stream -d /dev/ttyS2 -s ATTITUDE_CONTROLS -r 1
usleep 100000
mavlink stream -d /dev/ttyS2 -s NAMED_VALUE_FLOAT -r 100
usleep 100000
mavlink stream -d /dev/ttyS2 -s CAMERA_CAPTURE -r 1
usleep 100000
mavlink stream -d /dev/ttyS2 -s DISTANCE_SENSOR -r 1
usleep 100000
mavlink stream -d /dev/ttyS2 -s PARAM_VALUE -r 200


what I actually get in QGS are:
-HEARTBEAT
-SYS_STATUS
-PARAM_VALUE
-ATTITUDE
-ATTITUDE_QUATERNION
-LOCAL_POSITION_NED
-SERVO_OUTPUT_RAW
-MISSION_COUNT
-VFR_HUD
-COMMAND_LONG
-POSITION_TARGET_GLOBAL_INT
-HIHGRES_IMU
-STATUSTEXT


I already found out that the GPS Streams are missing because there is no GPS receiver connected at the moment. If I set "fake GPS" to "yes" in the init script, those streams will show up as well. But I cannot get ATTITUDE_TARGET working.

cheers
Marcel

**Comment by mhkabir** [comment]
Why did you put so many in extras.txt? You won't need to since you have set
the SYS_COMPANION parameter to 921600 for that ;)

This is probably a thing about thr fixed wing controller that the
controllers don't publish their targets from some reason. Unfortunately I
do not have a system which I can test on at the moment.

Post on px4users about it. Might be of some help.

Are your controller apps running? See in NuttX console please.

**Comment by psei0r** [comment]
I can try but this would just be an attempt to "dirty hack" the airplane config as said yourself before, right? Don't you think I should take a loot on the /init.d/rcS and try to setup my own px4 stack with only the things running that I need including a simple mixer for the outputs? I already tried to set CBRK_RATE_CTRL to 140253, because it says "This breaker disables the output of the system's rate controller and allows to send direct commands to the motors with a different app, even when attitude control is started." , but that didn't work either.

I looked through the rcS file today and I began to understand how it works, but there are so many if / else that depend on different system variables, that I haven't understood totally yet... Do you have some custom template for that file or a guide how to approach this? 

What are the basics I need?

I figured out that I need 

-serial driver
-uORB
-mavlink
-sensors
-controllers(?)
-basic mixer

Am I on the right track ? 

cheers 
Marcel

**Comment by mhkabir** [comment]
Apologies, but this is way beyond the scope of the mavros bug tracker ;)

I'd be happy to guide you in a months time when I'm free. If you go with
the hacky method, then offboard should work. This is because offboard
forwards the set points to the controllers. The controllers publish the
target messages.

What you want to do is directly forward servo values to the channels from
ROS, right?

**Comment by LorenzMeier** [comment]
I'd be happy to lend a hand. Can you contact me via Gitter chat?

**Comment by psei0r** [comment]
I'd love to! I just logged into gitter.im, but I dont know how to find you there, I never used it before... sorry...maybe you can contact me somehow so that I can respond ? Thanks!

**Comment by psei0r** [comment]
and @mhkabir : sorry I forgot to thank you as well, your information helped me alot !

**Comment by LorenzMeier** [comment]
http://gitter.im/PX4/Firmware

**Comment by psei0r** [comment]
@mhkabir :
Yes, I want to control the car via ROS messages. Our current car is driven by sending cmd_vel messages to an arduino/mpu6050 based controller running my own custom firmware on it. There I have direct access to the PWM outputs via I2C. But since we bought some pixhawks for research, I decided to use them to build a fleet of ROS driven RC cars.
