### ISSUE TITLE
frame of setpoint

### ISSUE THREAD

**Issue by MarcGyongyosi** [mavlink/mavros#288]
Hi, quick question - just to make sure everything will be working as expected during the next tests tomorrow: when I send a setpoint as PoseStamped on the mavros/setpoint_position/local topic does it take the frame into consideration? I.e. if I send a point x,y,z,yaw in the fcu frame, that is relative to the fcu itself, right? So If I were to send a PoseStamped in a different frame - e.g. local_origin, will it take that into consideration and transform properly?

Thanks!

Marc

**Comment by vooon** [comment]
I think, its local_origin, not body frame.
Not sure does tf translate or not...

**Comment by Royalcheese** [comment]
Are you overwriting the topic with your own talker ? Because i've done it, but i'm not sure if it just erase setpoint_pos topic or if it write data on it to make setpoint_pos plugin working. In that case you will have tf translating I suppose.

I'm interested about the results of your test, concerning what frame you have to send in PoseStamped if it do not bother you :)

**Comment by MarcGyongyosi** [comment]
I will test it as soon as I have some for test data from my localization framework in!

**Comment by Royalcheese** [comment]
I have z_fcu =  -z_sent , setting Posestamped.header.frame.id= "fcu", =1 ...
I must have misunderstood something...

**Comment by vooon** [comment]
@Royalcheese Frame conversion #49.

**Comment by Royalcheese** [comment]
Great ! thank you :)

**Comment by vooon** [comment]
I thin i can close this.
