### ISSUE TITLE
Altitude hold with barometer only?

### ISSUE THREAD

**Issue by Squizzy** [mavlink/mavros#426]
Hey there,

i want to control my yaw rates of my PX4 (PX4 Stack - no APM) via mavros. but it would be nice if the controller hold the altitude with barometer by itself. is this possible or is it necessary to program a PID for myself. this would be pain in the a** for me. 

in my vision i am sending an altitude and yaw rates and the controller does the rest.

greetings

**Comment by vooon** [comment]
That question for firmware team. As i know in such conditions you may not to use position setpoint
because imu not accuracy enough for tracking position in long term.
But perhaps you may try to combine attitude and setpoint_raw plugins, Last one provide identical message as mavlink SET_POSITION_TARGET_LOCAL_NED.
So you may ignore all except altitude. But again that question for firmware team.
