### ISSUE TITLE
fatal error: 'endian.h' file not found

### ISSUE THREAD

**Issue by eric1221bday** [mavlink/mavros#851]
As stated, compiling MAVROS on Mac will result in an `fatal error: 'endian.h' file not found` error in `include/mavlink/v2.0/common/../msgmap.hpp:4:10:`. Technically this is a mavlink issue, but mavlink actually compiles fine, it's just the generated header points to a file that doesn't exist and this error only pops up when you compile something else that uses mavlink, like mavros.

This is actually a long standing error on Mac, I've found the workaround to be found [here](https://www.snip2code.com/Snippet/1530728/ros-kinetic-mavros-on-Mac). Basically create `/usr/include/endian.h` from [this](https://gist.githubusercontent.com/yinyin/2027912/raw/6b3e394dc6a37817410d66d6ba4d7cd6b8d5d03d/endian.h). However this messing around with system header files is highly unsatisfactory and unsafe so I'm seeing if anyone can take a look at the included file and maybe come up with a solution.

**Comment by TSC21** [comment]
@eric1221bday this is not something that can be solved on our side. Some type of workaround can possibly be added to cmake, but we currently try to solve problems on supported platforms. Mac is not the case. So if you find a way that we can integrate this into the build system, great. Otherwise we don't have the bandwidth to help you out. Besides, I personally don't have a Mac to do the development.
